{
 "title": "JW-DPE-K8sMonitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum by (node) (kube_node_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods Per Namespace (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Namespaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (avg by (namespace) (kube_pod_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods Per Node (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum by (node) (kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# Pods ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (machine_memory_bytes/1024/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (instance:node_cpu_utilisation:rate5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (instance:node_memory_utilisation:ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Root Disk Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_filesystem_size_bytes{mountpoint='/'}/1024/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (node_network_speed_bytes{device=~\"en(.*)\"}/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Root Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (1-(node_filesystem_free_bytes{mountpoint='/'}/1024/1024/1024) / (node_filesystem_size_bytes{mountpoint='/'}/1024/1024/1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by (node_network_type)( label_replace(sum by (instance) (label_replace(sum by (instance) (sum by (instance) (irate(node_network_transmit_bytes_total[1m])/1024/1024)), \"instance\", \"$1\", \"instance\", \"(.*):9100\")), \"node_network_type\", \"$1, send\", \"instance\", \"(.*)\")  or label_replace(sum by (instance) (label_replace(sum by (instance) (sum by (instance) (irate(node_network_receive_bytes_total[1m])/1024/1024)), \"instance\", \"$1\", \"instance\", \"(.*):9100\")), \"node_network_type\", \"$1, recv\", \"instance\", \"(.*)\") )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaced Pod Placement",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (node, namespace, pod) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (persistentvolume) (kube_persistentvolume_capacity_bytes/1024/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim Storage Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaced Pods Count Per Node",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "label_replace(sum by (node, namespace) (kube_pod_info), \"node\",\"None\", \"node\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}